FROM ubuntu:24.04

MAINTAINER Evgeny Shtanov

# non-interactive
ENV DEBIAN_FRONTEND noninteractive

# install build dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential git ca-certificates cmake libssl-dev\
    capnproto libcapnp-dev libelf-dev libbpf-dev libpcap-dev libgrpc-dev libgrpc++-dev libprotobuf-dev\
    protobuf-compiler libprotoc-dev libprotobuf-dev protobuf-compiler-grpc libboost-dev\
    libboost-serialization-dev libboost-thread-dev libboost-regex-dev libboost-program-options-dev\
    libmongoc-dev liblog4cpp5-dev libncurses5-dev 

# absl
RUN apt-get install -y clang llvm llvm-dev lld tmux curl wget gdb 

RUN git clone https://github.com/AFLplusplus/AFLplusplus  && cd AFLplusplus && make && make install 

# Install cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN cp /root/.cargo/bin/* /bin/

# Install casr
RUN mkdir casr && git clone https://github.com/ispras/casr/
RUN cd casr/ && cargo build --release && cargo install casr
RUN cp /root/.cargo/bin/* /bin/


COPY src/ /src/
WORKDIR /src
RUN mkdir build && cd build && \
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DLINK_WITH_ABSL=ON -DENABLE_FUZZ_TEST=ON -DCMAKE_CXX_COMPILER=afl-clang-lto++ \
      -DCMAKE_CXX_FLAGS="-g -O0 -ggdb3 -fsanitize=address,bounds,undefined,null,float-divide-by-zero"   \
      && make -j$(nproc) parse_sflow_v5_packet_fuzz \
      && make -j$(nproc) process_netflow_packet_v5_fuzz
