FROM ubuntu:24.04

# non-interactive
ENV DEBIAN_FRONTEND noninteractive

# install build dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential git ca-certificates cmake libssl-dev\
    capnproto libcapnp-dev libelf-dev libbpf-dev libpcap-dev libgrpc-dev libgrpc++-dev libprotobuf-dev\
    protobuf-compiler libprotoc-dev libprotobuf-dev protobuf-compiler-grpc libboost-dev\
    libboost-serialization-dev libboost-thread-dev libboost-regex-dev libboost-program-options-dev\
    libmongoc-dev liblog4cpp5-dev libncurses5-dev 

# absl
RUN apt-get install -y clang llvm llvm-dev tmux 

RUN git clone https://github.com/AFLplusplus/AFLplusplus  && cd AFLplusplus && make && make install 

COPY src/ /src/
WORKDIR /src
RUN mkdir build && cd build && \
      cmake .. -DLINK_WITH_ABSL=ON -DCMAKE_CXX_COMPILER=afl-g++ \
      -DCMAKE_CXX_FLAGS="-g -fsanitize=address,bounds,undefined,null,float-divide-by-zero" \
      && make -j$(nproc)


 

