version: 2.1
parameters:
  fastnetmon_build_version:
    type: string
    default: "1.2.10"
orbs:
  win: circleci/windows@4.1
jobs:
  build_debian:
    parameters:
      docker_image:
        type: string
      distro_version:
        type: string
      distro_name: 
        type: string
      s3cmd_install_command:
        type: string
        default: "apt-get install -y s3cmd"
      resource_class:
        type: string
        default: large
      debian_package_architecture:
        type: string
        default: "amd64"
    machine:
      image: ubuntu-2204:current
    environment:
      DEBIAN_FRONTEND: noninteractive
    resource_class: << parameters.resource_class >>
    steps:
      - run: sudo docker run --name  linux_docker -d -t << parameters.docker_image >>
      - run: sudo docker exec linux_docker apt-get update; true
      - run: sudo docker exec linux_docker apt-get install -y perl wget git
      - run: sudo docker exec --env DEBIAN_FRONTEND linux_docker bash -c "<< parameters.s3cmd_install_command >>"
      - run: sudo docker exec linux_docker git clone https://github.com/pavel-odintsov/fastnetmon.git
      - run:
          name: install_gcc
          no_output_timeout: 120m 
          command: sudo -E docker exec --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY linux_docker perl fastnetmon/src/scripts/install_fastnetmon_dependencies.pl gcc_12_1_0
      - run:
          name: install_dependencies
          no_output_timeout: 180m
          command: sudo -E docker exec --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY linux_docker perl fastnetmon/src/scripts/install_fastnetmon_dependencies.pl
      - run: sudo docker exec linux_docker perl fastnetmon/src/scripts/fastnetmon_build.pl
      - run: sudo docker exec linux_docker perl fastnetmon/src/scripts/build_library_bundle.pl /opt/fastnetmon_libraries_bundle.tar.gz
      - run: sudo docker exec linux_docker fastnetmon/src/scripts/build_any_package.pl deb /opt/fastnetmon_libraries_bundle.tar.gz << pipeline.parameters.fastnetmon_build_version >> << parameters.distro_name >> << parameters.distro_version >>
      - run: sudo -E docker exec --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY linux_docker s3cmd --disable-multipart  --host=storage.googleapis.com --host-bucket="%(bucket).storage.googleapis.com" put /tmp/fastnetmon_<< pipeline.parameters.fastnetmon_build_version >>_<< parameters.debian_package_architecture >>.deb s3://community_packages/<< pipeline.parameters.fastnetmon_build_version >>/<< parameters.distro_name >>/<< parameters.distro_version >>/fastnetmon_<< pipeline.parameters.fastnetmon_build_version >>_<< parameters.debian_package_architecture >>.deb
      - run: sudo docker exec linux_docker cp fastnetmon/src/fastnetmon.conf /etc/fastnetmon.conf
      - run: sudo docker exec linux_docker ldd /opt/fastnetmon-community/app/bin/fastnetmon
      - run: sudo docker exec linux_docker ldd /opt/fastnetmon-community/app/bin/fastnetmon_client
      - run: sudo docker exec linux_docker ldd /opt/fastnetmon-community/app/bin/fastnetmon_api_client
      - run: sudo docker exec linux_docker /opt/fastnetmon-community/app/bin/fastnetmon_api_client --help
      - run: sudo docker exec linux_docker /opt/fastnetmon-community/app/bin/fastnetmon_client --help
      - run: sudo docker exec linux_docker /opt/fastnetmon-community/app/bin/fastnetmon --configuration_check

workflows:
  version: 2
  all_distros:
    jobs:
      - build_debian:
          docker_image: "ubuntu:jammy"
          distro_version: "22.04"
          name: "ubuntu2204"
          distro_name: "ubuntu"
      - build_debian:
          docker_image: "ubuntu:noble"
          distro_version: "24.04"
          name: "ubuntu2404"
          distro_name: "ubuntu"
      - build_debian:
          docker_image: "ubuntu:jammy"
          distro_version: "22.04"
          name: "ubuntu2204_arm"
          distro_name: "ubuntu"
          resource_class: "arm.large"
          debian_package_architecture: "arm64"
      - build_debian:
          docker_image: "ubuntu:noble"
          distro_version: "24.04"
          name: "ubuntu2404_arm"
          distro_name: "ubuntu"
          resource_class: "arm.large"
          debian_package_architecture: "arm64"
      - build_debian:
          docker_image: "ubuntu:focal"
          distro_version: "20.04"
          name: "ubuntu2004"
          distro_name: "ubuntu"
      - build_debian:
          docker_image: "ubuntu:focal"
          distro_version: "20.04"
          name: "ubuntu2004_arm"
          distro_name: "ubuntu"
          resource_class: "arm.large"
          debian_package_architecture: "arm64"
      - build_debian:
          docker_image: "debian:bullseye"
          distro_version: "11"
          name: "debian11"
          distro_name: "debian"
      - build_debian:
          docker_image: "debian:bullseye"
          distro_version: "11"
          name: "debian11_arm"
          distro_name: "debian"
          resource_class: "arm.large"
          debian_package_architecture: "arm64"
      - build_debian:
          docker_image: "debian:bookworm"
          distro_version: "12"
          name: "debian12"
          distro_name: "debian"
      - build_debian:
          docker_image: "debian:bookworm"
          distro_version: "12"
          name: "debian12_arm"
          distro_name: "debian"
          resource_class: "arm.large"
          debian_package_architecture: "arm64"

