.\" Manpage for fastnetmon.
.\" Contact pavel.odintsov@gmail.com to correct errors or typos.
.TH man 1 "04 Jun 2015" "1.1.2" "fastnetmon man page"
.SH NAME
FastNetMon \- a high performance DoS/DDoS load analyzer built on top of multiple packet capture 
.SH SYNOPSIS
fastnetmon [--daemonize]
.SH DESCRIPTION
FastNetMon - a high performance DoS/DDoS load analyzer built on top of multiple packet capture engines (NetFlow, IPFIX, sFLOW, netmap, PF_RING, PCAP).

For more information about configuration please look at comments in /etc/fastnetmon.conf and check GitHub page: https://github.com/FastVPSEestiOu/fastnetmon.
.SH OPTIONS
The fastnetmon has only single command line option --daemonize which used for forking and detaching it from the terminal.
.SH SEE ALSO
fastnetmon_client(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Pavel Odintsov (pavel.odintsov@gmail.com)
