#!/bin/sh
set -eu

#CONFIG_DIR="$SNAP_COMMON/etc"
#LOG_DIR="$SNAP_COMMON/log"
CONFIG_DIR="/etc"
LOG_DIR="/var/log/fastnetmon_attacks"

mkdir -p "$CONFIG_DIR"
mkdir -p "$LOG_DIR"

copy_if_missing() {
    src="$1"
    dst="$2"

    if [ ! -f "$dst" ]; then
        if [ -f "$src" ]; then
            cp "$src" "$dst"
        else
            echo "Missing default file: $src" >&2
            exit 1
        fi
    fi
}

copy_config_if_missing() {
    src="$1"
    dst="$2"

    if [ ! -f "$dst" ]; then
        if [ ! -f "$src" ]; then
            echo "Missing default config file: $src" >&2
            exit 1
        fi

        cp "$src" "$dst"

        # Edit only the newly created writable copy.
        sed -i "s|^networks_list_path *=.*|networks_list_path = $CONFIG_DIR/networks_list|" "$dst"
        sed -i "s|^networks_whitelist_path *=.*|networks_whitelist_path = $CONFIG_DIR/networks_whitelist|" "$dst"

        echo "Created initial config: $dst" >&2
    else
        echo "Config already exists, leaving unchanged: $dst" >&2
    fi
}


copy_config_if_missing "$SNAP/etc/fastnetmon.conf" "$CONFIG_DIR/fastnetmon.conf"
copy_if_missing "$SNAP/etc/networks_list" "$CONFIG_DIR/networks_list"
copy_if_missing "$SNAP/etc/networks_whitelist" "$CONFIG_DIR/networks_whitelist"


mkdir -p /var/log/fastnetmon_attacks
